# Generated by Django 5.0.2 on 2024-03-26 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessidea',
            name='competitive_advantage',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessidea',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='businessidea',
            name='marketing_strategy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessidea',
            name='potential_challenges',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessidea',
            name='resources_needed',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessidea',
            name='target_audience',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
