# Generated by Django 5.0.2 on 2024-03-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_businessidea_competitive_advantage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessidea',
            name='average_capital',
        ),
        migrations.AlterField(
            model_name='businessidea',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='businessidea',
            name='idea',
            field=models.TextField(),
        ),
    ]
