# Generated by Django 5.0.2 on 2024-03-28 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_user_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='loanlimit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
