# Generated by Django 5.0.2 on 2024-03-28 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='loanlimit',
        ),
        migrations.AddField(
            model_name='account',
            name='loan_limit',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10),
        ),
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='session_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
